language: c

dist: trusty
sudo: required

addons:
        apt:
                update: true
                sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise-3.8
                packages:
                        - linux-headers-$(uname -r)
                        - gcc
                        - linux-libc-dev                
                        - libpopt-dev
                        - libssl-dev
                        - libnuma-dev
                        - curl
compiler:
        - gcc
        


install:
       - curl www.qq.com
       - curl 192.168.94.133
       - ssh xdc@192.168.94.133  
       - uname -r
       - ls /lib/modules/4.4.0-101-generic
       - cd dpdk-stable-17.05.2
       - sed -i "s/pci_intx_mask_supported(dev)/pci_intx_mask_supported(dev)||true/g" lib/librte_eal/linuxapp/igb_uio/igb_uio.c
       - patch -p 1 < 0001-PATCH-kni-use-netlink-event-for-multicast-driver-par.patch
       - make config T=x86_64-native-linuxapp-gcc
       - make -j40
       - export RTE_SDK=$PWD
       
script:
       - ssh root@192.168.94.143
       - sudo sh -c ' echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages'
       - cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
       - sudo sh -c ' mkdir /mnt/huge'
       - sudo sh -c ' mount -t hugetlbfs nodev /mnt/huge'
       - sudo sh -c ' modprobe uio'
       - sudo sh -c  'insmod build/kmod/igb_uio.ko'
       -  sudo sh -c 'insmod build/kmod/rte_kni.ko'
       - ./usertools/dpdk-devbind.py --status
       - ip a
       -  ifdown eth0
       - ./usertools/dpdk-devbind.py -b igb_uio 0000:00:04.0
       - cd app/test-pmd/
       - make RTE_TARGET=build
       - ./build/app/testpmd -c 3 -n 2 -- -i
